### ISSUE TITLE
States/provinces for other countries

### ISSUE THREAD

**Issue by elijahrona** [rOpenGov/giscoR#49]
First of all, thank you so much for the package.

If I want to create a map of Nigeria, I only see the map (as in the outline) without the states nor state borders.

Imagining I want to compare the states of Nigeria, is it possible with your package?

Thank you.

**Comment by dieghernan** [comment]
Hi @elijahrona 

Although **giscoR** provides country-level data for all the countries in the world, the sub-national data is only available for European countries (and more specifically countries members/candidates of the European Union).  On this, remember that **giscoR** uses the data available on GISCO (the the Geographic Information System of the European Commission).

If you need to get sub-national shapefiles I recommend you the following data souces:

- [GADM](https://gadm.org/): GADM provides maps and spatial data for all countries and their sub-divisions.
- [geoboundaries](https://www.geoboundaries.org/): Open, free and research-ready database of political administrative boundaries. 

The good news is that there are a bunch of **R** packages that allows you to query these databases straight on your session:
- **GADM**: Packages [**geodata**](https://cran.r-project.org/package=geodata) (on CRAN) and [**GADMTools**](https://github.com/IamKDO/GADMTools) (previously on CRAN but was removed, now available on GitHub).
- **geoboundaries**: Package [**rgeoboundaries**](https://dickoa.gitlab.io/rgeoboundaries) (on GitHub).

Specifically, if you want political boundaries of any African country, It is worth also to check the package [**afriadmin**](https://github.com/afrimapr/afriadmin) (GitHub), by the [afrimapr project](https://afrimapr.org/). This package uses either **geoboundaries** or **GADM** via the option `datasource`.

Finally, I also recommend the package [**countrycodes** ](https://cran.r-project.org/package=countrycode) (CRAN) to easily convert between names and country codes. This is useful since some packages would request the country names while others requires the ISO3 code.


Find here a reproducible example showing hot to download geographic data for Nigeria with each of the suggested packages:

``` r
# For plotting
library(ggplot2)


# On CRAN ----
# install.packages("geodata")

library(geodata)
#> Loading required package: terra
#> terra 1.6.47
nig_geodata <- geodata::gadm("Nigeria",
  level = 1,
  path = tempdir()
) |>
  sf::st_as_sf() # Provided in SpatVector (terra) format, convert it to sf


ggplot(nig_geodata) +
  geom_sf() +
  labs(
    title = "Nigeria, Level 1",
    subtitle = "package geodata (CRAN)"
  )
```

![](https://i.imgur.com/pxOja1l.png)

``` r

# On GitHub ----

# remotes::install_github("IamKDO/GADMTools")
library(GADMTools)

# Note the $sf at the end
nig_gadmtools <- gadm_sf_loadCountries("NGA", level = 1)$sf


ggplot(nig_gadmtools) +
  geom_sf() +
  labs(
    title = "Nigeria, Level 1",
    subtitle = "package GADMTools (GitHub)"
  )
#> old-style crs object detected; please recreate object with a recent sf::st_crs()
#> old-style crs object detected; please recreate object with a recent sf::st_crs()
#> old-style crs object detected; please recreate object with a recent sf::st_crs()
```

![](https://i.imgur.com/x04y4Dr.png)

``` r

# remotes::install_github("wmgeolab/rgeoboundaries")

library(rgeoboundaries)

ggplot(nig_geobondaries) +
  geom_sf() +
  labs(
    title = "Nigeria, Level 1",
    subtitle = "package rgeoboundaries (GitHub)"
  )
```

![](https://i.imgur.com/OE6U01X.png)

``` r


# Specific for Africa
# remotes::install_github("afrimapr/afriadmin")
library(afriadmin)
nig_afriadmin <- afriadmin("nigeria", level = 1, plot = FALSE)


ggplot(nig_afriadmin) +
  geom_sf() +
  labs(
    title = "Nigeria, Level 1",
    subtitle = "package afriadmin (GitHub)"
  )
```

![](https://i.imgur.com/QThfbls.png)

<sup>Created on 2023-01-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by elijahrona** [comment]
OMG thanks a lot for your help.

I will try them then. I really appreciate you.

**Comment by dieghernan** [comment]
Check also this app to compare both **geoboundaries** and**GADM** data sources on a interactive map (kudos to @andysouth)!

https://andysouth.shinyapps.io/afriadmin-compare/

**Comment by elijahrona** [comment]
> Check also this app to compare both **geoboundaries** and **GADM** data sources on a interactive map (kudos to @andysouth)!
> 
> https://andysouth.shinyapps.io/afriadmin-compare/

Thanks a lot. I am currently practicing.![20230109_111118.jpg](https://user-images.githubusercontent.com/20893206/211284989-8c992503-c04c-4862-b55d-0e8bf07f0f8a.jpg)
